name: Lint and Build
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install, Lint, and Build
        run: |
          npm install
          npm run lint
          npm run build
